chore(deps): update aqua-installer (#137)
[![Mend Renovate logo
banner](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| [aquaproj/aqua](https://togithub.com/aquaproj/aqua) | minor |
`v2.16.4` -> `v2.17.4` |
|
[aquaproj/aqua-installer](https://togithub.com/aquaproj/aqua-installer)
| minor | `v2.1.3` -> `v2.2.0` |

---

### Release Notes

<details>
<summary>aquaproj/aqua (aquaproj/aqua)</summary>

### [`v2.17.4`](https://togithub.com/aquaproj/aqua/releases/tag/v2.17.4)

[Compare
Source](https://togithub.com/aquaproj/aqua/compare/v2.17.3...v2.17.4)

[Pull
Requests](https://togithub.com/aquaproj/aqua/pulls?q=is%3Apr+milestone%3Av2.17.4)
|
[Issues](https://togithub.com/aquaproj/aqua/issues?q=is%3Aissue+milestone%3Av2.17.4)
| https://github.com/aquaproj/aqua/compare/v2.17.3...v2.17.4

##### Others

[#&#8203;2401](https://togithub.com/aquaproj/aqua/issues/2401)
[#&#8203;2483](https://togithub.com/aquaproj/aqua/issues/2483) Release
aqua to
[Winget](https://learn.microsoft.com/en-us/windows/package-manager/winget/)
🎉


[https://github.com/microsoft/winget-pkgs/pull/127174](https://togithub.com/microsoft/winget-pkgs/pull/127174)

### [`v2.17.3`](https://togithub.com/aquaproj/aqua/releases/tag/v2.17.3)

[Compare
Source](https://togithub.com/aquaproj/aqua/compare/v2.17.2...v2.17.3)

[Pull
Requests](https://togithub.com/aquaproj/aqua/pulls?q=is%3Apr+milestone%3Av2.17.3)
|
[Issues](https://togithub.com/aquaproj/aqua/issues?q=is%3Aissue+milestone%3Av2.17.3)
| https://github.com/aquaproj/aqua/compare/v2.17.2...v2.17.3

##### Bug Fixes 🐞

[#&#8203;2476](https://togithub.com/orgs/aquaproj/discussions/2476)
[#&#8203;2479](https://togithub.com/aquaproj/aqua/issues/2479) policy:
fix a bug that the [Git Repository root's policy
file](https://aquaproj.github.io/docs/reference/security/policy-as-code/git-policy/)
doesn't work well in working trees

##### Others

[#&#8203;2470](https://togithub.com/aquaproj/aqua/issues/2470)
[#&#8203;2472](https://togithub.com/aquaproj/aqua/issues/2472) Replace
the third party library github.com/codingsince1985/checksum with
standard libraries

This library caused the bug
[#&#8203;2467](https://togithub.com/aquaproj/aqua/issues/2467) and we
can replace the library with standard libraries easily.
We should use standard libraries as much as possible.

[#&#8203;2473](https://togithub.com/aquaproj/aqua/issues/2473) Revert
[#&#8203;2469](https://togithub.com/aquaproj/aqua/issues/2469)

[#&#8203;2469](https://togithub.com/aquaproj/aqua/issues/2469) was
required to resolve
[#&#8203;2467](https://togithub.com/aquaproj/aqua/issues/2467) , but
[#&#8203;2467](https://togithub.com/aquaproj/aqua/issues/2467) was
resolved by
[#&#8203;2472](https://togithub.com/aquaproj/aqua/issues/2472) so
[#&#8203;2469](https://togithub.com/aquaproj/aqua/issues/2469) is
unnecessary anymore.


[https://github.com/aquaproj/aqua/pull/2472#issuecomment-1812023515](https://togithub.com/aquaproj/aqua/pull/2472#issuecomment-1812023515)

### [`v2.17.2`](https://togithub.com/aquaproj/aqua/releases/tag/v2.17.2)

[Compare
Source](https://togithub.com/aquaproj/aqua/compare/v2.17.1...v2.17.2)

[Pull
Requests](https://togithub.com/aquaproj/aqua/pulls?q=is%3Apr+milestone%3Av2.17.2)
|
[Issues](https://togithub.com/aquaproj/aqua/issues?q=is%3Aissue+milestone%3Av2.17.2)
| https://github.com/aquaproj/aqua/compare/v2.17.1...v2.17.2

##### Bug Fixes

[#&#8203;2457](https://togithub.com/orgs/aquaproj/discussions/2457)
[#&#8203;2458](https://togithub.com/aquaproj/aqua/issues/2458) update:
Fix a panic when trying to update commands unmanaged by aqua
[@&#8203;dreamjz](https://togithub.com/dreamjz)
[#&#8203;2468](https://togithub.com/aquaproj/aqua/issues/2468) policy
init: Fix typo in CLI output [@&#8203;ka2n](https://togithub.com/ka2n)
[#&#8203;2467](https://togithub.com/aquaproj/aqua/issues/2467)
[#&#8203;2469](https://togithub.com/aquaproj/aqua/issues/2469)
update-checksum: Copy an asset to a temporal file to calculate the
checksum correctly

##### update-checksum: Copy an asset to a temporal file to calculate the
checksum correctly

[#&#8203;2467](https://togithub.com/aquaproj/aqua/issues/2467)
[#&#8203;2469](https://togithub.com/aquaproj/aqua/issues/2469)

This fixes a bug that the checksum verification of aws/aws-cli fails
because the expected checksum of aws/aws-cli is wrong.

If you face the issue already, please remove checksums of aws/aws-cli
from aqua-checksums.json and run `aqua update-checksum` with aqua
v2.17.2 or newer.

aqua-checksums.json

```json
    // Delete this element
    {
      "id": "http/awscli.amazonaws.com/AWSCLIV2-2.13.35.pkg",
      "checksum": "520E1CB49004ECED7DB1CFE70E6FA73EFC6EDDF1CDB38AF535D126F1DB6574C8",
      "algorithm": "sha256"
    },
```

##### 🎉 New Contributors

Thank you for your contribution!

[@&#8203;ka2n](https://togithub.com/ka2n)
[#&#8203;2468](https://togithub.com/aquaproj/aqua/issues/2468)

### [`v2.17.1`](https://togithub.com/aquaproj/aqua/releases/tag/v2.17.1)

[Compare
Source](https://togithub.com/aquaproj/aqua/compare/v2.17.0...v2.17.1)

[Pull
Requests](https://togithub.com/aquaproj/aqua/pulls?q=is%3Apr+milestone%3Av2.17.1)
|
[Issues](https://togithub.com/aquaproj/aqua/issues?q=is%3Aissue+milestone%3Av2.17.1)
| https://github.com/aquaproj/aqua/compare/v2.17.0...v2.17.1

##### Bug Fixes 🐞

[#&#8203;2456](https://togithub.com/aquaproj/aqua/issues/2456)
generate-registry: Fix a bug that the order of versions in pkg.yaml is
wrong

### [`v2.17.0`](https://togithub.com/aquaproj/aqua/releases/tag/v2.17.0)

[Compare
Source](https://togithub.com/aquaproj/aqua/compare/v2.16.4...v2.17.0)

[Pull
Requests](https://togithub.com/aquaproj/aqua/pulls?q=is%3Apr+milestone%3Av2.17.0)
|
[Issues](https://togithub.com/aquaproj/aqua/issues?q=is%3Aissue+milestone%3Av2.17.0)
| https://github.com/aquaproj/aqua/compare/v2.16.4...v2.17.0

##### Features

[#&#8203;2355](https://togithub.com/aquaproj/aqua/issues/2355)
[#&#8203;2447](https://togithub.com/aquaproj/aqua/issues/2447) Limit the
number of versions retrieved by command `generate` and `update`
[@&#8203;dreamjz](https://togithub.com/dreamjz)

With aqua v2.16.4 or earlier, `aqua generate -s` and `aqua update -s`
retrieved all versions and these commands couldn't change the number of
versions.
This release adds the command line option `--limit/-l` to these
commands.
The value of this option is the number of versions.
The default value is `30`.
If the value is less than zero, all versions are retrieved.

This change would reduced useless GitHub API calls and make these
commands faster.

e.g.

```sh
aqua g -s # Retrieve 30 versions
aqua g -s -l 10 # Retrieve 10 versions
aqua g -s -l -1 # Retrieve all versions
```

[#&#8203;2445](https://togithub.com/aquaproj/aqua/issues/2445) Change
the default checksum algorithm from `sha512` to `sha256`

sha256 is enough.
We don't need to use sha512.

[#&#8203;2428](https://togithub.com/aquaproj/aqua/issues/2428) Add an
alias of `update-checksum` command

```sh
aqua upc
```

[#&#8203;2105](https://togithub.com/aquaproj/aqua/issues/2105)
[#&#8203;2425](https://togithub.com/aquaproj/aqua/issues/2425)
[#&#8203;2413](https://togithub.com/aquaproj/aqua/issues/2413)
generate-registry: Improve the format of `version_overrides` and improve
the logic to generate `version_overrides`

##### Bug Fixes 🐞

[#&#8203;2444](https://togithub.com/aquaproj/aqua/issues/2444)
generate-registry: Fix checksum filename for sha1

##### Others

[#&#8203;2436](https://togithub.com/aquaproj/aqua/issues/2436)
chore(deps): update dependency slsa-framework/slsa-verifier to v2.4.1
[#&#8203;2395](https://togithub.com/aquaproj/aqua/issues/2395) change
the format of prebuilt binaries for Windows to zip

Before:

aqua_windows_amd64.tar.gz
aqua_windows_arm64.tar.gz

After:

aqua_windows_amd64.zip
aqua_windows_arm64.zip

On Windows zip is more user friendly than tar.gz.
And to support Winget for Windows, it seems we need to change the format
to zip.

-
[https://github.com/aquaproj/aqua/issues/2401](https://togithub.com/aquaproj/aqua/issues/2401)

<!---->

      • winget
⨯ release failed after 1m11s error=no zip archives found matching
goos=[windows] goarch=[amd64 386] goamd64=v1 ids=[]
    Error: Process completed with exit code 1.

⚠️ To upgrade aqua to v2.17.0 or newer on Windows, you need to upgrade
aqua to v2.16.1 ~ v2.16.4 once.

e.g.

```sh
aqua upa v2.16.4
aqua upa
```

##### New Contributors 🎉

Thank you for your contribution!

[@&#8203;dreamjz](https://togithub.com/dreamjz)
[#&#8203;2447](https://togithub.com/aquaproj/aqua/issues/2447)

</details>

<details>
<summary>aquaproj/aqua-installer (aquaproj/aqua-installer)</summary>

###
[`v2.2.0`](https://togithub.com/aquaproj/aqua-installer/releases/tag/v2.2.0)

[Compare
Source](https://togithub.com/aquaproj/aqua-installer/compare/v2.1.3...v2.2.0)


[Issues](https://togithub.com/aquaproj/aqua-installer/issues?q=is%3Aissue+milestone%3Av2.2.0)
| [Pull
Requests](https://togithub.com/aquaproj/aqua-installer/pulls?q=is%3Apr+milestone%3Av2.2.0)
| https://github.com/aquaproj/aqua-installer/compare/v2.1.3...v2.2.0

##### Features

[#&#8203;365](https://togithub.com/aquaproj/aqua-installer/issues/365)
[#&#8203;550](https://togithub.com/aquaproj/aqua-installer/issues/550)
[#&#8203;551](https://togithub.com/aquaproj/aqua-installer/issues/551)
Output the guide to set the environment variable `PATH`

`aqua-installer` outputs the following guide.

    ===============================================================
[INFO] aqua is installed into /root/.local/share/aquaproj-aqua/bin/aqua
    [INFO] Please add the path to the environment variable "PATH"
[INFO] export
PATH=${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:$PATH
    ===============================================================

[#&#8203;551](https://togithub.com/aquaproj/aqua-installer/issues/551)
Use wget if curl isn't found

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "after 4pm on thursday" in timezone
America/Los_Angeles, Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config help](https://togithub.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/scottames/dots).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy41OS44IiwidXBkYXRlZEluVmVyIjoiMzcuNTkuOCIsInRhcmdldEJyYW5jaCI6Im1haW4ifQ==-->

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Scott Ames <scott@ames.sh>